## -------------------------------------------------------------------
## Helper to build and run an Onboarding dockerized environment for local
## development. This tool is very useful to avoid problems witg arm 
## environments, specially with Mac ARM64.
## -------------------------------------------------------------------
